<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Patient;
use App\Models\Clinic;
use Carbon\Carbon;

class PatientsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Creates 20 realistic patient records with Philippine-specific data
     */
    public function run(): void
    {
        // Get Enhaynes Dental Clinic
        $clinic = Clinic::where('slug', 'enhaynes-dental-clinic')->first();
        
        if (!$clinic) {
            $this->command->error('❌ Enhaynes Dental Clinic not found! Please run TestAccountsSeeder first.');
            return;
        }

        $patients = [
            // Patient 1 - Regular Adult Female
            [
                'clinic_id' => $clinic->id,
                'first_name' => 'Maria',
                'last_name' => 'Santos',
                'email' => 'maria.santos@gmail.com',
                'phone_number' => '09171234567',
                'date_of_birth' => Carbon::now()->subYears(32)->format('Y-m-d'),
                'gender' => 'female',
                'street_address' => '123 Rizal Street',
                'barangay_code' => '160202001', // Surigao City barangay
                'city_municipality_code' => '160202', // Surigao City
                'province_code' => '1602', // Surigao del Norte
                'region_code' => '16', // Caraga
                'postal_code' => '8400',
                'medical_history' => json_encode(['Hypertension (controlled with medication)']),
                'allergies' => json_encode(['Penicillin']),
                'emergency_contact_name' => 'Juan Santos',
                'emergency_contact_number' => '09181234567',
                'emergency_contact_relationship' => 'Husband',
                'blood_type' => 'O+',
                'occupation' => 'Teacher',
                'marital_status' => 'married',
                'last_dental_visit' => 'Within 6 months',
                'category' => 'regular',
                'notes' => 'Regular patient, prefers morning appointments',
            ],

            // Patient 2 - VIP Adult Male
            [
                'clinic_id' => $clinic->id,
                'first_name' => 'Juan',
                'last_name' => 'Dela Cruz',
                'email' => 'juan.delacruz@yahoo.com',
                'phone_number' => '09189876543',
                'date_of_birth' => Carbon::now()->subYears(45)->format('Y-m-d'),
                'gender' => 'male',
                'street_address' => '456 Bonifacio Avenue',
                'barangay_code' => '160202002',
                'city_municipality_code' => '160202',
                'province_code' => '1602',
                'region_code' => '16',
                'postal_code' => '8400',
                'medical_history' => json_encode(['Diabetes Type 2', 'High Cholesterol']),
                'allergies' => json_encode([]),
                'emergency_contact_name' => 'Ana Dela Cruz',
                'emergency_contact_number' => '09199876543',
                'emergency_contact_relationship' => 'Wife',
                'blood_type' => 'A+',
                'occupation' => 'Business Owner',
                'marital_status' => 'married',
                'last_dental_visit' => 'Within 3 months',
                'category' => 'vip',
                'notes' => 'VIP patient, requires detailed explanations',
            ],

            // Patient 3 - Pediatric Female
            [
                'clinic_id' => $clinic->id,
                'first_name' => 'Sofia',
                'last_name' => 'Reyes',
                'email' => null,
                'phone_number' => '09156789012',
                'date_of_birth' => Carbon::now()->subYears(8)->format('Y-m-d'),
                'gender' => 'female',
                'street_address' => '789 Luna Street',
                'barangay_code' => '160202003',
                'city_municipality_code' => '160202',
                'province_code' => '1602',
                'region_code' => '16',
                'postal_code' => '8400',
                'medical_history' => json_encode([]),
                'allergies' => json_encode(['Latex']),
                'emergency_contact_name' => 'Carmen Reyes',
                'emergency_contact_number' => '09156789012',
                'emergency_contact_relationship' => 'Mother',
                'blood_type' => 'B+',
                'occupation' => 'Student',
                'marital_status' => 'single',
                'last_dental_visit' => 'No previous visit',
                'category' => 'pediatric',
                'notes' => 'First dental visit, may need extra reassurance',
            ],

            // Patient 4 - Senior Male
            [
                'clinic_id' => $clinic->id,
                'first_name' => 'Roberto',
                'last_name' => 'Garcia',
                'email' => 'roberto.garcia@hotmail.com',
                'phone_number' => '09123456789',
                'date_of_birth' => Carbon::now()->subYears(68)->format('Y-m-d'),
                'gender' => 'male',
                'street_address' => '321 Mabini Street',
                'barangay_code' => '160202004',
                'city_municipality_code' => '160202',
                'province_code' => '1602',
                'region_code' => '16',
                'postal_code' => '8400',
                'medical_history' => json_encode(['Hypertension', 'Arthritis', 'Previous heart surgery']),
                'allergies' => json_encode(['Aspirin']),
                'emergency_contact_name' => 'Miguel Garcia',
                'emergency_contact_number' => '09133456789',
                'emergency_contact_relationship' => 'Son',
                'blood_type' => 'AB+',
                'occupation' => 'Retired',
                'marital_status' => 'widowed',
                'last_dental_visit' => 'Within 1 year',
                'category' => 'senior',
                'notes' => 'Senior citizen discount applicable, needs dentures',
            ],

            // Patient 5 - New Patient Female
            [
                'clinic_id' => $clinic->id,
                'first_name' => 'Ana',
                'last_name' => 'Mendoza',
                'email' => 'ana.mendoza@gmail.com',
                'phone_number' => '09167890123',
                'date_of_birth' => Carbon::now()->subYears(25)->format('Y-m-d'),
                'gender' => 'female',
                'street_address' => '654 Del Pilar Street',
                'barangay_code' => '160202005',
                'city_municipality_code' => '160202',
                'province_code' => '1602',
                'region_code' => '16',
                'postal_code' => '8400',
                'medical_history' => json_encode([]),
                'allergies' => json_encode([]),
                'emergency_contact_name' => 'Rosa Mendoza',
                'emergency_contact_number' => '09177890123',
                'emergency_contact_relationship' => 'Mother',
                'blood_type' => 'O-',
                'occupation' => 'Nurse',
                'marital_status' => 'single',
                'last_dental_visit' => 'No previous visit',
                'category' => 'new',
                'notes' => 'First time patient, works in healthcare',
            ],

            // Patient 6 - Regular Adult Male
            [
                'clinic_id' => $clinic->id,
                'first_name' => 'Carlos',
                'last_name' => 'Ramos',
                'email' => 'carlos.ramos@yahoo.com',
                'phone_number' => '09198765432',
                'date_of_birth' => Carbon::now()->subYears(38)->format('Y-m-d'),
                'gender' => 'male',
                'street_address' => '987 Quezon Avenue',
                'barangay_code' => '160202006',
                'city_municipality_code' => '160202',
                'province_code' => '1602',
                'region_code' => '16',
                'postal_code' => '8400',
                'medical_history' => json_encode(['Asthma']),
                'allergies' => json_encode(['Sulfa drugs']),
                'emergency_contact_name' => 'Linda Ramos',
                'emergency_contact_number' => '09188765432',
                'emergency_contact_relationship' => 'Wife',
                'blood_type' => 'A-',
                'occupation' => 'Engineer',
                'marital_status' => 'married',
                'last_dental_visit' => 'More than 1 year',
                'category' => 'returning',
                'notes' => 'Returning patient after 2 years',
            ],

            // Patient 7 - Pediatric Male
            [
                'clinic_id' => $clinic->id,
                'first_name' => 'Miguel',
                'last_name' => 'Torres',
                'email' => null,
                'phone_number' => '09145678901',
                'date_of_birth' => Carbon::now()->subYears(6)->format('Y-m-d'),
                'gender' => 'male',
                'street_address' => '234 Aguinaldo Street',
                'barangay_code' => '160202007',
                'city_municipality_code' => '160202',
                'province_code' => '1602',
                'region_code' => '16',
                'postal_code' => '8400',
                'medical_history' => json_encode([]),
                'allergies' => json_encode([]),
                'emergency_contact_name' => 'Elena Torres',
                'emergency_contact_number' => '09145678901',
                'emergency_contact_relationship' => 'Mother',
                'blood_type' => 'B-',
                'occupation' => 'Student',
                'marital_status' => 'single',
                'last_dental_visit' => 'Within 6 months',
                'category' => 'pediatric',
                'notes' => 'Good behavior during procedures',
            ],

            // Patient 8 - Regular Female
            [
                'clinic_id' => $clinic->id,
                'first_name' => 'Teresa',
                'last_name' => 'Cruz',
                'email' => 'teresa.cruz@gmail.com',
                'phone_number' => '09112345678',
                'date_of_birth' => Carbon::now()->subYears(42)->format('Y-m-d'),
                'gender' => 'female',
                'street_address' => '567 Roxas Boulevard',
                'barangay_code' => '160202008',
                'city_municipality_code' => '160202',
                'province_code' => '1602',
                'region_code' => '16',
                'postal_code' => '8400',
                'medical_history' => json_encode(['Thyroid disorder']),
                'allergies' => json_encode([]),
                'emergency_contact_name' => 'Pedro Cruz',
                'emergency_contact_number' => '09122345678',
                'emergency_contact_relationship' => 'Husband',
                'blood_type' => 'O+',
                'occupation' => 'Accountant',
                'marital_status' => 'married',
                'last_dental_visit' => 'Within 3 months',
                'category' => 'regular',
                'notes' => 'Prefers afternoon appointments',
            ],

            // Patient 9 - Young Adult Male
            [
                'clinic_id' => $clinic->id,
                'first_name' => 'Rafael',
                'last_name' => 'Aquino',
                'email' => 'rafael.aquino@gmail.com',
                'phone_number' => '09187654321',
                'date_of_birth' => Carbon::now()->subYears(22)->format('Y-m-d'),
                'gender' => 'male',
                'street_address' => '890 Magsaysay Avenue',
                'barangay_code' => '160202009',
                'city_municipality_code' => '160202',
                'province_code' => '1602',
                'region_code' => '16',
                'postal_code' => '8400',
                'medical_history' => json_encode([]),
                'allergies' => json_encode([]),
                'emergency_contact_name' => 'Gloria Aquino',
                'emergency_contact_number' => '09197654321',
                'emergency_contact_relationship' => 'Mother',
                'blood_type' => 'A+',
                'occupation' => 'College Student',
                'marital_status' => 'single',
                'last_dental_visit' => 'Within 1 year',
                'category' => 'new',
                'notes' => 'Interested in teeth whitening',
            ],

            // Patient 10 - Middle-aged Female
            [
                'clinic_id' => $clinic->id,
                'first_name' => 'Luz',
                'last_name' => 'Bautista',
                'email' => 'luz.bautista@yahoo.com',
                'phone_number' => '09134567890',
                'date_of_birth' => Carbon::now()->subYears(55)->format('Y-m-d'),
                'gender' => 'female',
                'street_address' => '123 Osmena Street',
                'barangay_code' => '160202010',
                'city_municipality_code' => '160202',
                'province_code' => '1602',
                'region_code' => '16',
                'postal_code' => '8400',
                'medical_history' => json_encode(['Osteoporosis', 'Hypertension']),
                'allergies' => json_encode([]),
                'emergency_contact_name' => 'Ramon Bautista',
                'emergency_contact_number' => '09144567890',
                'emergency_contact_relationship' => 'Husband',
                'blood_type' => 'B+',
                'occupation' => 'Government Employee',
                'marital_status' => 'married',
                'last_dental_visit' => 'Within 6 months',
                'category' => 'regular',
                'notes' => 'Requires gentle handling due to osteoporosis',
            ],

            // Patient 11 - Young Female
            [
                'clinic_id' => $clinic->id,
                'first_name' => 'Isabella',
                'last_name' => 'Fernandez',
                'email' => 'isabella.fernandez@gmail.com',
                'phone_number' => '09165432109',
                'date_of_birth' => Carbon::now()->subYears(19)->format('Y-m-d'),
                'gender' => 'female',
                'street_address' => '456 Burgos Street',
                'barangay_code' => '160202011',
                'city_municipality_code' => '160202',
                'province_code' => '1602',
                'region_code' => '16',
                'postal_code' => '8400',
                'medical_history' => json_encode([]),
                'allergies' => json_encode([]),
                'emergency_contact_name' => 'Carmen Fernandez',
                'emergency_contact_number' => '09175432109',
                'emergency_contact_relationship' => 'Mother',
                'blood_type' => 'AB-',
                'occupation' => 'College Student',
                'marital_status' => 'single',
                'last_dental_visit' => 'No previous visit',
                'category' => 'new',
                'notes' => 'Interested in braces consultation',
            ],

            // Patient 12 - Adult Male
            [
                'clinic_id' => $clinic->id,
                'first_name' => 'Eduardo',
                'last_name' => 'Villanueva',
                'email' => 'eduardo.villanueva@hotmail.com',
                'phone_number' => '09198761234',
                'date_of_birth' => Carbon::now()->subYears(50)->format('Y-m-d'),
                'gender' => 'male',
                'street_address' => '789 Laurel Avenue',
                'barangay_code' => '160202012',
                'city_municipality_code' => '160202',
                'province_code' => '1602',
                'region_code' => '16',
                'postal_code' => '8400',
                'medical_history' => json_encode(['Heart disease', 'Takes blood thinners']),
                'allergies' => json_encode(['Codeine']),
                'emergency_contact_name' => 'Rosario Villanueva',
                'emergency_contact_number' => '09188761234',
                'emergency_contact_relationship' => 'Wife',
                'blood_type' => 'O-',
                'occupation' => 'Businessman',
                'marital_status' => 'married',
                'last_dental_visit' => 'Within 3 months',
                'category' => 'vip',
                'notes' => 'Requires medical clearance for procedures',
            ],

            // Patient 13 - Teen Female
            [
                'clinic_id' => $clinic->id,
                'first_name' => 'Gabriela',
                'last_name' => 'Morales',
                'email' => null,
                'phone_number' => '09123456780',
                'date_of_birth' => Carbon::now()->subYears(14)->format('Y-m-d'),
                'gender' => 'female',
                'street_address' => '321 Jacinto Street',
                'barangay_code' => '160202013',
                'city_municipality_code' => '160202',
                'province_code' => '1602',
                'region_code' => '16',
                'postal_code' => '8400',
                'medical_history' => json_encode([]),
                'allergies' => json_encode([]),
                'emergency_contact_name' => 'Maria Morales',
                'emergency_contact_number' => '09123456780',
                'emergency_contact_relationship' => 'Mother',
                'blood_type' => 'A+',
                'occupation' => 'High School Student',
                'marital_status' => 'single',
                'last_dental_visit' => 'Within 6 months',
                'category' => 'pediatric',
                'notes' => 'Currently wearing braces',
            ],

            // Patient 14 - Senior Female
            [
                'clinic_id' => $clinic->id,
                'first_name' => 'Esperanza',
                'last_name' => 'Santiago',
                'email' => null,
                'phone_number' => '09156781234',
                'date_of_birth' => Carbon::now()->subYears(72)->format('Y-m-d'),
                'gender' => 'female',
                'street_address' => '654 Taft Avenue',
                'barangay_code' => '160202014',
                'city_municipality_code' => '160202',
                'province_code' => '1602',
                'region_code' => '16',
                'postal_code' => '8400',
                'medical_history' => json_encode(['Diabetes', 'Hypertension', 'Osteoarthritis']),
                'allergies' => json_encode([]),
                'emergency_contact_name' => 'Jose Santiago',
                'emergency_contact_number' => '09166781234',
                'emergency_contact_relationship' => 'Husband',
                'blood_type' => 'B+',
                'occupation' => 'Retired Teacher',
                'marital_status' => 'married',
                'last_dental_visit' => 'More than 1 year',
                'category' => 'senior',
                'notes' => 'Needs complete dentures, senior discount',
            ],

            // Patient 15 - Adult Male
            [
                'clinic_id' => $clinic->id,
                'first_name' => 'Antonio',
                'last_name' => 'Lopez',
                'email' => 'antonio.lopez@gmail.com',
                'phone_number' => '09189012345',
                'date_of_birth' => Carbon::now()->subYears(35)->format('Y-m-d'),
                'gender' => 'male',
                'street_address' => '987 Harrison Street',
                'barangay_code' => '160202015',
                'city_municipality_code' => '160202',
                'province_code' => '1602',
                'region_code' => '16',
                'postal_code' => '8400',
                'medical_history' => json_encode([]),
                'allergies' => json_encode([]),
                'emergency_contact_name' => 'Patricia Lopez',
                'emergency_contact_number' => '09199012345',
                'emergency_contact_relationship' => 'Wife',
                'blood_type' => 'O+',
                'occupation' => 'IT Professional',
                'marital_status' => 'married',
                'last_dental_visit' => 'Within 1 year',
                'category' => 'regular',
                'notes' => 'Prefers weekend appointments',
            ],

            // Patient 16 - Young Adult Female
            [
                'clinic_id' => $clinic->id,
                'first_name' => 'Beatriz',
                'last_name' => 'Navarro',
                'email' => 'beatriz.navarro@yahoo.com',
                'phone_number' => '09112340987',
                'date_of_birth' => Carbon::now()->subYears(28)->format('Y-m-d'),
                'gender' => 'female',
                'street_address' => '234 Recto Avenue',
                'barangay_code' => '160202016',
                'city_municipality_code' => '160202',
                'province_code' => '1602',
                'region_code' => '16',
                'postal_code' => '8400',
                'medical_history' => json_encode(['Migraine']),
                'allergies' => json_encode([]),
                'emergency_contact_name' => 'Ricardo Navarro',
                'emergency_contact_number' => '09122340987',
                'emergency_contact_relationship' => 'Father',
                'blood_type' => 'A-',
                'occupation' => 'Marketing Manager',
                'marital_status' => 'single',
                'last_dental_visit' => 'Within 3 months',
                'category' => 'regular',
                'notes' => 'Sensitive to bright lights',
            ],

            // Patient 17 - Middle-aged Male
            [
                'clinic_id' => $clinic->id,
                'first_name' => 'Fernando',
                'last_name' => 'Castillo',
                'email' => 'fernando.castillo@gmail.com',
                'phone_number' => '09187651098',
                'date_of_birth' => Carbon::now()->subYears(48)->format('Y-m-d'),
                'gender' => 'male',
                'street_address' => '567 Legarda Street',
                'barangay_code' => '160202017',
                'city_municipality_code' => '160202',
                'province_code' => '1602',
                'region_code' => '16',
                'postal_code' => '8400',
                'medical_history' => json_encode(['Kidney stones history']),
                'allergies' => json_encode([]),
                'emergency_contact_name' => 'Cecilia Castillo',
                'emergency_contact_number' => '09197651098',
                'emergency_contact_relationship' => 'Wife',
                'blood_type' => 'B-',
                'occupation' => 'Architect',
                'marital_status' => 'married',
                'last_dental_visit' => 'Within 6 months',
                'category' => 'regular',
                'notes' => 'Prefers detailed treatment explanations',
            ],

            // Patient 18 - Young Female
            [
                'clinic_id' => $clinic->id,
                'first_name' => 'Cristina',
                'last_name' => 'Diaz',
                'email' => 'cristina.diaz@gmail.com',
                'phone_number' => '09165439876',
                'date_of_birth' => Carbon::now()->subYears(24)->format('Y-m-d'),
                'gender' => 'female',
                'street_address' => '890 Evangelista Street',
                'barangay_code' => '160202018',
                'city_municipality_code' => '160202',
                'province_code' => '1602',
                'region_code' => '16',
                'postal_code' => '8400',
                'medical_history' => json_encode([]),
                'allergies' => json_encode([]),
                'emergency_contact_name' => 'Luisa Diaz',
                'emergency_contact_number' => '09175439876',
                'emergency_contact_relationship' => 'Mother',
                'blood_type' => 'AB+',
                'occupation' => 'Graphic Designer',
                'marital_status' => 'single',
                'last_dental_visit' => 'No previous visit',
                'category' => 'new',
                'notes' => 'Interested in cosmetic dentistry',
            ],

            // Patient 19 - Adult Male
            [
                'clinic_id' => $clinic->id,
                'first_name' => 'Vicente',
                'last_name' => 'Pascual',
                'email' => 'vicente.pascual@hotmail.com',
                'phone_number' => '09198760123',
                'date_of_birth' => Carbon::now()->subYears(41)->format('Y-m-d'),
                'gender' => 'male',
                'street_address' => '123 Gomez Street',
                'barangay_code' => '160202019',
                'city_municipality_code' => '160202',
                'province_code' => '1602',
                'region_code' => '16',
                'postal_code' => '8400',
                'medical_history' => json_encode(['Gout']),
                'allergies' => json_encode([]),
                'emergency_contact_name' => 'Angelica Pascual',
                'emergency_contact_number' => '09188760123',
                'emergency_contact_relationship' => 'Wife',
                'blood_type' => 'O+',
                'occupation' => 'Chef',
                'marital_status' => 'married',
                'last_dental_visit' => 'More than 1 year',
                'category' => 'returning',
                'notes' => 'Works irregular hours, flexible scheduling needed',
            ],

            // Patient 20 - Senior Male
            [
                'clinic_id' => $clinic->id,
                'first_name' => 'Alfredo',
                'last_name' => 'Mercado',
                'email' => null,
                'phone_number' => '09134561234',
                'date_of_birth' => Carbon::now()->subYears(75)->format('Y-m-d'),
                'gender' => 'male',
                'street_address' => '456 Ponce Street',
                'barangay_code' => '160202020',
                'city_municipality_code' => '160202',
                'province_code' => '1602',
                'region_code' => '16',
                'postal_code' => '8400',
                'medical_history' => json_encode(['Prostate cancer survivor', 'Hypertension', 'Hearing impairment']),
                'allergies' => json_encode(['Iodine']),
                'emergency_contact_name' => 'Roberto Mercado',
                'emergency_contact_number' => '09144561234',
                'emergency_contact_relationship' => 'Son',
                'blood_type' => 'A+',
                'occupation' => 'Retired Military',
                'marital_status' => 'widowed',
                'last_dental_visit' => 'Within 1 year',
                'category' => 'senior',
                'notes' => 'Hearing impaired, speak clearly and face patient. Senior discount.',
            ],
        ];

        foreach ($patients as $patient) {
            Patient::create($patient);
        }

        $this->command->info('✅ Successfully created 20 patient records for Enhaynes Dental Clinic!');
        $this->command->info('   👥 Regular: 7 patients');
        $this->command->info('   ⭐ VIP: 2 patients');
        $this->command->info('   👶 Pediatric: 4 patients');
        $this->command->info('   👴 Senior: 3 patients');
        $this->command->info('   🆕 New: 4 patients');
    }
}
