<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Service;
use App\Models\Clinic;

class ServicesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Creates 20 realistic dental services for Enhaynes Dental Clinic
     */
    public function run(): void
    {
        // Get Enhaynes Dental Clinic
        $clinic = Clinic::where('slug', 'enhaynes-dental-clinic')->first();
        
        if (!$clinic) {
            $this->command->error('❌ Enhaynes Dental Clinic not found! Please run TestAccountsSeeder first.');
            return;
        }

        $services = [
            // PREVENTIVE SERVICES (5)
            [
                'clinic_id' => $clinic->id,
                'name' => 'Dental Cleaning (Prophylaxis)',
                'description' => 'Professional teeth cleaning to remove plaque, tartar, and stains. Includes polishing and fluoride treatment.',
                'category' => 'preventive',
                'subcategory' => 'cleaning',
                'code' => 'PREV-001',
                'price' => 1500.00,
                'duration_minutes' => 45,
                'procedure_details' => 'Scaling, polishing, and fluoride application to maintain oral health and prevent cavities.',
                'preparation_instructions' => 'Brush teeth before appointment. Inform dentist of any medical conditions.',
                'post_procedure_care' => 'Avoid eating for 30 minutes after fluoride treatment. Maintain regular brushing and flossing.',
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'clinic_id' => $clinic->id,
                'name' => 'Fluoride Treatment',
                'description' => 'Application of fluoride varnish to strengthen tooth enamel and prevent decay.',
                'category' => 'preventive',
                'subcategory' => 'treatment',
                'code' => 'PREV-002',
                'price' => 500.00,
                'duration_minutes' => 20,
                'procedure_details' => 'Topical fluoride application to strengthen enamel and reduce cavity risk.',
                'preparation_instructions' => 'Clean teeth before treatment for better absorption.',
                'post_procedure_care' => 'Do not eat or drink for 30 minutes. Avoid hot beverages for 4 hours.',
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'clinic_id' => $clinic->id,
                'name' => 'Dental X-Ray (Panoramic)',
                'description' => 'Comprehensive panoramic X-ray showing all teeth, jaws, and surrounding structures.',
                'category' => 'preventive',
                'subcategory' => 'diagnostic',
                'code' => 'PREV-003',
                'price' => 800.00,
                'duration_minutes' => 15,
                'procedure_details' => 'Digital panoramic radiograph for comprehensive dental assessment.',
                'preparation_instructions' => 'Remove all metal objects from head and neck area.',
                'post_procedure_care' => 'No special care required. Results will be discussed with dentist.',
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'clinic_id' => $clinic->id,
                'name' => 'Dental Consultation',
                'description' => 'Initial consultation and oral examination by our experienced dentist.',
                'category' => 'preventive',
                'subcategory' => 'consultation',
                'code' => 'PREV-004',
                'price' => 500.00,
                'duration_minutes' => 30,
                'procedure_details' => 'Comprehensive oral examination, diagnosis, and treatment planning.',
                'preparation_instructions' => 'Bring previous dental records if available.',
                'post_procedure_care' => 'Follow recommended treatment plan.',
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'clinic_id' => $clinic->id,
                'name' => 'Dental Sealants',
                'description' => 'Protective coating applied to molars to prevent cavities, especially for children.',
                'category' => 'preventive',
                'subcategory' => 'treatment',
                'code' => 'PREV-005',
                'price' => 1200.00,
                'duration_minutes' => 30,
                'procedure_details' => 'Application of resin sealant to chewing surfaces of back teeth.',
                'preparation_instructions' => 'Teeth should be clean and dry.',
                'post_procedure_care' => 'Avoid sticky foods for 24 hours. Maintain good oral hygiene.',
                'is_active' => true,
                'sort_order' => 5,
            ],

            // RESTORATIVE SERVICES (5)
            [
                'clinic_id' => $clinic->id,
                'name' => 'Dental Filling (Composite)',
                'description' => 'Tooth-colored composite resin filling to restore decayed or damaged teeth.',
                'category' => 'restorative',
                'subcategory' => 'filling',
                'code' => 'REST-001',
                'price' => 2000.00,
                'duration_minutes' => 60,
                'procedure_details' => 'Removal of decay and restoration with composite resin material matched to tooth color.',
                'preparation_instructions' => 'Eat before appointment as mouth will be numb for several hours.',
                'post_procedure_care' => 'Avoid hard foods for 24 hours. Sensitivity is normal for a few days.',
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'clinic_id' => $clinic->id,
                'name' => 'Dental Crown (Porcelain)',
                'description' => 'Custom-made porcelain crown to restore and protect damaged teeth.',
                'category' => 'restorative',
                'subcategory' => 'crown',
                'code' => 'REST-002',
                'price' => 15000.00,
                'duration_minutes' => 120,
                'procedure_details' => 'Tooth preparation, impression taking, temporary crown placement, and permanent crown cementation.',
                'preparation_instructions' => 'Two visits required. Temporary crown will be placed first.',
                'post_procedure_care' => 'Avoid sticky foods with temporary crown. Maintain good oral hygiene.',
                'is_active' => true,
                'sort_order' => 7,
            ],
            [
                'clinic_id' => $clinic->id,
                'name' => 'Root Canal Treatment',
                'description' => 'Endodontic treatment to save infected or damaged tooth by removing infected pulp.',
                'category' => 'restorative',
                'subcategory' => 'endodontics',
                'code' => 'REST-003',
                'price' => 8000.00,
                'duration_minutes' => 90,
                'procedure_details' => 'Removal of infected pulp, cleaning and shaping of root canals, and sealing.',
                'preparation_instructions' => 'Take prescribed antibiotics if given. Eat before appointment.',
                'post_procedure_care' => 'Avoid chewing on treated tooth. Take pain medication as prescribed.',
                'is_active' => true,
                'sort_order' => 8,
            ],
            [
                'clinic_id' => $clinic->id,
                'name' => 'Dental Bridge (3-Unit)',
                'description' => 'Fixed dental bridge to replace missing teeth using adjacent teeth as support.',
                'category' => 'restorative',
                'subcategory' => 'bridge',
                'code' => 'REST-004',
                'price' => 25000.00,
                'duration_minutes' => 150,
                'procedure_details' => 'Preparation of abutment teeth, impression, temporary bridge, and permanent bridge cementation.',
                'preparation_instructions' => 'Multiple visits required. Good oral hygiene essential.',
                'post_procedure_care' => 'Use floss threader for cleaning under bridge. Regular dental checkups.',
                'is_active' => true,
                'sort_order' => 9,
            ],
            [
                'clinic_id' => $clinic->id,
                'name' => 'Dentures (Complete Set)',
                'description' => 'Full set of removable dentures to replace all missing teeth in upper or lower jaw.',
                'category' => 'restorative',
                'subcategory' => 'dentures',
                'code' => 'REST-005',
                'price' => 30000.00,
                'duration_minutes' => 180,
                'procedure_details' => 'Multiple appointments for impressions, try-in, and final fitting of complete dentures.',
                'preparation_instructions' => 'Several visits required for proper fitting and adjustments.',
                'post_procedure_care' => 'Remove and clean dentures daily. Soak overnight in denture solution.',
                'is_active' => true,
                'sort_order' => 10,
            ],

            // COSMETIC SERVICES (3)
            [
                'clinic_id' => $clinic->id,
                'name' => 'Teeth Whitening (Professional)',
                'description' => 'Professional in-office teeth whitening for a brighter, whiter smile.',
                'category' => 'cosmetic',
                'subcategory' => 'whitening',
                'code' => 'COSM-001',
                'price' => 12000.00,
                'duration_minutes' => 90,
                'procedure_details' => 'Application of professional-grade whitening gel with LED light activation.',
                'preparation_instructions' => 'Teeth should be clean. Avoid staining foods 24 hours before.',
                'post_procedure_care' => 'Avoid dark-colored foods and drinks for 48 hours. Use sensitivity toothpaste if needed.',
                'is_active' => true,
                'sort_order' => 11,
            ],
            [
                'clinic_id' => $clinic->id,
                'name' => 'Dental Veneers (Porcelain)',
                'description' => 'Custom porcelain veneers to improve appearance of front teeth.',
                'category' => 'cosmetic',
                'subcategory' => 'veneers',
                'code' => 'COSM-002',
                'price' => 18000.00,
                'duration_minutes' => 120,
                'procedure_details' => 'Minimal tooth preparation, impression, temporary veneers, and permanent veneer bonding.',
                'preparation_instructions' => 'Two visits required. Discuss desired shade with dentist.',
                'post_procedure_care' => 'Avoid hard foods. Wear night guard if you grind teeth.',
                'is_active' => true,
                'sort_order' => 12,
            ],
            [
                'clinic_id' => $clinic->id,
                'name' => 'Gum Contouring',
                'description' => 'Cosmetic reshaping of gum line for improved smile aesthetics.',
                'category' => 'cosmetic',
                'subcategory' => 'gum_treatment',
                'code' => 'COSM-003',
                'price' => 10000.00,
                'duration_minutes' => 60,
                'procedure_details' => 'Laser or surgical reshaping of gum tissue for balanced smile.',
                'preparation_instructions' => 'Consultation required to discuss desired outcome.',
                'post_procedure_care' => 'Soft diet for 3 days. Avoid hot foods. Use prescribed mouthwash.',
                'is_active' => true,
                'sort_order' => 13,
            ],

            // ORTHODONTICS (2)
            [
                'clinic_id' => $clinic->id,
                'name' => 'Braces Installation (Metal)',
                'description' => 'Traditional metal braces for comprehensive orthodontic treatment.',
                'category' => 'orthodontics',
                'subcategory' => 'braces',
                'code' => 'ORTHO-001',
                'price' => 35000.00,
                'duration_minutes' => 120,
                'procedure_details' => 'Bonding of metal brackets and placement of archwire for teeth alignment.',
                'preparation_instructions' => 'Teeth cleaning recommended before installation. Monthly adjustments required.',
                'post_procedure_care' => 'Avoid hard and sticky foods. Maintain excellent oral hygiene. Use orthodontic wax for irritation.',
                'is_active' => true,
                'sort_order' => 14,
            ],
            [
                'clinic_id' => $clinic->id,
                'name' => 'Retainer (After Braces)',
                'description' => 'Custom retainer to maintain teeth position after orthodontic treatment.',
                'category' => 'orthodontics',
                'subcategory' => 'retainer',
                'code' => 'ORTHO-002',
                'price' => 5000.00,
                'duration_minutes' => 30,
                'procedure_details' => 'Impression taking and fitting of custom retainer.',
                'preparation_instructions' => 'Wear as instructed by orthodontist.',
                'post_procedure_care' => 'Clean retainer daily. Store in case when not wearing.',
                'is_active' => true,
                'sort_order' => 15,
            ],

            // SURGERY (3)
            [
                'clinic_id' => $clinic->id,
                'name' => 'Tooth Extraction (Simple)',
                'description' => 'Removal of damaged or problematic tooth under local anesthesia.',
                'category' => 'surgery',
                'subcategory' => 'extraction',
                'code' => 'SURG-001',
                'price' => 2500.00,
                'duration_minutes' => 30,
                'procedure_details' => 'Local anesthesia and careful extraction of tooth.',
                'preparation_instructions' => 'Eat before appointment. Inform dentist of medications.',
                'post_procedure_care' => 'Bite on gauze for 30 minutes. Avoid hot foods and smoking for 24 hours.',
                'is_active' => true,
                'sort_order' => 16,
            ],
            [
                'clinic_id' => $clinic->id,
                'name' => 'Wisdom Tooth Extraction',
                'description' => 'Surgical removal of impacted or problematic wisdom teeth.',
                'category' => 'surgery',
                'subcategory' => 'extraction',
                'code' => 'SURG-002',
                'price' => 5000.00,
                'duration_minutes' => 60,
                'procedure_details' => 'Surgical extraction of wisdom tooth with local anesthesia or sedation.',
                'preparation_instructions' => 'Fasting may be required if sedation is used. Arrange transportation.',
                'post_procedure_care' => 'Apply ice pack. Take prescribed medications. Soft diet for 3 days.',
                'is_active' => true,
                'sort_order' => 17,
            ],
            [
                'clinic_id' => $clinic->id,
                'name' => 'Dental Implant (Single)',
                'description' => 'Surgical placement of titanium implant to replace missing tooth root.',
                'category' => 'surgery',
                'subcategory' => 'implant',
                'code' => 'SURG-003',
                'price' => 50000.00,
                'duration_minutes' => 180,
                'procedure_details' => 'Surgical placement of implant, healing period, and crown placement.',
                'preparation_instructions' => 'Multiple visits over several months. Good oral health required.',
                'post_procedure_care' => 'Soft diet for 1 week. Avoid smoking. Maintain excellent oral hygiene.',
                'is_active' => true,
                'sort_order' => 18,
            ],

            // PEDIATRIC (2)
            [
                'clinic_id' => $clinic->id,
                'name' => 'Pediatric Dental Checkup',
                'description' => 'Comprehensive dental examination and cleaning for children.',
                'category' => 'pediatric',
                'subcategory' => 'checkup',
                'code' => 'PED-001',
                'price' => 800.00,
                'duration_minutes' => 30,
                'procedure_details' => 'Gentle examination, cleaning, and fluoride treatment for children.',
                'preparation_instructions' => 'Explain procedure to child in positive terms. Bring favorite toy.',
                'post_procedure_care' => 'Encourage regular brushing. Limit sugary snacks.',
                'is_active' => true,
                'sort_order' => 19,
            ],
            [
                'clinic_id' => $clinic->id,
                'name' => 'Pediatric Tooth Extraction',
                'description' => 'Gentle extraction of baby teeth or problematic teeth in children.',
                'category' => 'pediatric',
                'subcategory' => 'extraction',
                'code' => 'PED-002',
                'price' => 1500.00,
                'duration_minutes' => 30,
                'procedure_details' => 'Gentle extraction with local anesthesia and child-friendly approach.',
                'preparation_instructions' => 'Reassure child. Light meal before appointment.',
                'post_procedure_care' => 'Soft foods. Avoid hot drinks. Rinse gently with salt water.',
                'is_active' => true,
                'sort_order' => 20,
            ],
        ];

        foreach ($services as $service) {
            Service::create($service);
        }

        $this->command->info('✅ Successfully created 20 dental services for Enhaynes Dental Clinic!');
    }
}
