-- Seeder: Insert permissions data
-- File: permissions_data.sql

INSERT INTO permissions (name, display_name, description, category, created_at, updated_at) VALUES
('view_patients', 'View Patients', 'Access patient records and information', 'patient_management', NOW(), NOW()),
('add_patients', 'Add Patients', 'Create new patient records', 'patient_management', NOW(), NOW()),
('edit_patients', 'Edit Patients', 'Modify patient information', 'patient_management', NOW(), NOW()),
('delete_patients', 'Delete Patients', 'Remove patient records', 'patient_management', NOW(), NOW()),
('view_appointments', 'View Appointments', 'Access appointment schedules and information', 'appointment_management', NOW(), NOW()),
('create_appointments', 'Create Appointments', 'Schedule new appointments', 'appointment_management', NOW(), NOW()),
('edit_appointments', 'Edit Appointments', 'Modify appointment details', 'appointment_management', NOW(), NOW()),
('delete_appointments', 'Delete Appointments', 'Cancel or remove appointments', 'appointment_management', NOW(), NOW()),
('assign_dentists', 'Assign Dentists', 'Assign dentists to appointments', 'appointment_management', NOW(), NOW()),
('view_treatments', 'View Treatments', 'Access treatment records and history', 'treatment_management', NOW(), NOW()),
('create_treatments', 'Create Treatments', 'Create new treatment plans', 'treatment_management', NOW(), NOW()),
('edit_treatments', 'Edit Treatments', 'Modify treatment records', 'treatment_management', NOW(), NOW()),
('delete_treatments', 'Delete Treatments', 'Remove treatment records', 'treatment_management', NOW(), NOW()),
('view_inventory', 'View Inventory', 'Access inventory and stock information', 'inventory_management', NOW(), NOW()),
('add_inventory', 'Add Inventory', 'Add new inventory items', 'inventory_management', NOW(), NOW()),
('edit_inventory', 'Edit Inventory', 'Modify inventory information', 'inventory_management', NOW(), NOW()),
('delete_inventory', 'Delete Inventory', 'Remove inventory items', 'inventory_management', NOW(), NOW()),
('manage_suppliers', 'Manage Suppliers', 'Create, edit, and delete supplier information', 'inventory_management', NOW(), NOW()),
('view_payments', 'View Payments', 'Access payment records and financial information', 'payment_management', NOW(), NOW()),
('process_payments', 'Process Payments', 'Process and manage payments', 'payment_management', NOW(), NOW()),
('refund_payments', 'Refund Payments', 'Process payment refunds', 'payment_management', NOW(), NOW()),
('view_services', 'View Services', 'Access service catalog', 'service_management', NOW(), NOW()),
('manage_services', 'Manage Services', 'Create, edit, and delete services', 'service_management', NOW(), NOW()),
('view_staff', 'View Staff', 'Access staff information', 'staff_management', NOW(), NOW()),
('add_staff', 'Add Staff', 'Create new staff members', 'staff_management', NOW(), NOW()),
('edit_staff', 'Edit Staff', 'Modify staff information', 'staff_management', NOW(), NOW()),
('delete_staff', 'Delete Staff', 'Remove staff members', 'staff_management', NOW(), NOW()),
('view_schedules', 'View Schedules', 'Access dentist schedules', 'schedule_management', NOW(), NOW()),
('manage_dentist_schedules', 'Manage Dentist Schedules', 'Create, edit, and delete dentist schedules', 'schedule_management', NOW(), NOW()),
('manage_clinic', 'Manage Clinic', 'Manage clinic settings and profile', 'clinic_management', NOW(), NOW());
